"""
Event Announcer - Handles follow, sub, and cheer announcements.

Reactions are generated by the personality engine so the co-host stays in
character exactly when it matters most -- the moments viewers spend money on.
The random templates below remain the fallback for a failed or disabled LLM
path, so an event is never silently dropped.
"""
import asyncio
import logging
import json
import random
from datetime import datetime, timedelta
from typing import Optional

logger = logging.getLogger(__name__)


class EventAnnouncer:
    """Announces follows, subs, and cheers."""

    def __init__(self, bot):
        self.bot = bot
        self.enabled = True

        # In-character reactions via the personality engine (templates are the
        # fallback). Tunable in bot_settings.json -> event_reactions.
        cfg = {}
        try:
            with open('bot_settings.json', 'r') as f:
                cfg = json.load(f).get('event_reactions') or {}
        except Exception as e:  # noqa: BLE001 - settings are optional
            logger.debug(f"No event_reactions settings: {e}")
        self.llm_reactions = bool(cfg.get('enabled', True))
        self.reaction_timeout = float(cfg.get('timeout_s', 8.0))
        self.reactions_generated = 0
        self.reactions_fell_back = 0

        # Cooldowns to prevent spam
        self.last_follow_time: Optional[datetime] = None
        self.follow_cooldown = 10  # seconds between follow announcements
        # Redemptions are the one event a viewer can fire on a whim: points
        # accrue just by watching, so a cheap reward can be redeemed several
        # times a minute. Subs and cheers cost real money and are rare, so
        # they stay uncapped; this one needs a floor or the co-host narrates
        # every hydrate reminder.
        self.last_redemption_time: Optional[datetime] = None
        self.redemption_cooldown = 60  # seconds between redemption reactions
        self.redemptions_suppressed = 0
        self.follow_queue = []  # Queue follows to batch announce
        # Recipients seen via channel.subscribe(is_gift) since the last gift
        # event; drained when the gift bomb itself is announced.
        self.gift_recipients = []

        # Message templates
        self.follow_messages = [
            "Welcome to the community, {user}!",
            "Hey {user}, thanks for the follow! Glad to have you!",
            "{user} just followed! Welcome aboard!",
            "New follower alert! Welcome {user}!",
        ]

        self.sub_messages = [
            "HUGE thanks to {user} for subscribing!",
            "{user} just subscribed! You're amazing!",
            "Welcome to the sub club, {user}! Thank you!",
            "{user} with the sub! Let's gooo!",
        ]

        self.resub_messages = [
            "{user} resubbed for {months} months! Incredible loyalty!",
            "{months} months of support from {user}! Thank you so much!",
            "{user} keeping the streak alive at {months} months!",
        ]

        self.gift_sub_messages = [
            "{user} just gifted {count} sub(s)! What a legend!",
            "Gift sub alert! {user} gifted {count} to the community!",
            "{user} spreading the love with {count} gift sub(s)!",
        ]

        self.cheer_messages = [
            "{user} cheered {bits} bits! Thank you!",
            "{bits} bits from {user}! You're awesome!",
            "Cheer alert! {user} with {bits} bits!",
        ]

        self.big_cheer_messages = [
            "MASSIVE cheer! {user} just dropped {bits} bits!",
            "WOW! {user} with {bits} bits! Absolutely incredible!",
            "{bits} BITS from {user}! The chat goes wild!",
        ]

    async def handle_follow(self, event: dict):
        """Handle follow event."""
        if not self.enabled:
            return

        user = event.get('user_name') or 'Someone'

        # Check cooldown
        now = datetime.now()
        if self.last_follow_time:
            elapsed = (now - self.last_follow_time).total_seconds()
            if elapsed < self.follow_cooldown:
                # Queue for batch announcement
                self.follow_queue.append(user)
                logger.debug(f"Follow queued: {user} (cooldown)")
                return

        self.last_follow_time = now

        # Include any queued follows
        if self.follow_queue:
            users = self.follow_queue + [user]
            self.follow_queue = []
            if len(users) > 3:
                message = f"Welcome to all our new followers: {', '.join(users[:3])} and {len(users)-3} more!"
            else:
                message = f"Welcome to our new followers: {', '.join(users)}!"
            await self._announce(message)
            self._remember(f"new followers: {', '.join(users)}")
            logger.info(f"Follows announced: {len(users)}")
            return

        await self._react(
            scenario=(f"{user} just followed the channel for the first time. "
                      f"Welcome them in character, in one short line."),
            actor=user,
            fallback=random.choice(self.follow_messages).format(user=user),
            note=f"{user} followed",
        )
        logger.info(f"Follow announced: {user}")

    async def handle_subscribe(self, event: dict):
        """Handle subscription event."""
        if not self.enabled:
            return

        user = event.get('user_name') or 'Someone'
        tier = event.get('tier') or '1000'  # 1000, 2000, 3000
        is_gift = event.get('is_gift', False)

        # Determine tier name
        tier_names = {'1000': 'Tier 1', '2000': 'Tier 2', '3000': 'Tier 3'}
        tier_name = tier_names.get(tier, 'Tier 1')

        if is_gift:
            # This is someone receiving a gift
            gifter = event.get('gifter_name', 'Anonymous')
            scenario = (f"{user} just received a gifted subscription from {gifter}. "
                        f"React in character in one short line.")
            fallback = f"{user} just got a gift sub from {gifter}! Welcome!"
            note = f"{user} got a gift sub from {gifter}"
        else:
            tier_note = "" if tier == '1000' else f" at {tier_name}"
            scenario = (f"{user} just subscribed{tier_note}. React in character "
                        f"in one short line -- they paid, so land it.")
            fallback = random.choice(self.sub_messages).format(user=user)
            if tier != '1000':
                fallback = f"{tier_name} sub! {fallback}"
            note = f"{user} subscribed{tier_note}"

        await self._react(scenario=scenario, actor=user, fallback=fallback,
                          priority="high", note=note)
        logger.info(f"Sub announced: {user} ({tier_name})")

    async def handle_resub(self, event: dict):
        """Handle resubscription event."""
        if not self.enabled:
            return

        user = event.get('user_name') or 'Someone'
        try:
            months = max(1, int(event.get('cumulative_months') or 1))
        except (TypeError, ValueError):
            months = 1
        # channel.subscription.message nests the text; a null message object
        # would break .get() chaining
        message_text = (event.get('message') or {}).get('text') or ''

        fallback = random.choice(self.resub_messages).format(user=user, months=months)
        scenario = (f"{user} just resubscribed for {months} months running. "
                    f"React in character in one short line.")
        if message_text:
            fallback += f" They said: \"{message_text[:100]}\""
            scenario += f" Their resub message was: \"{message_text[:100]}\""

        await self._react(scenario=scenario, actor=user, fallback=fallback,
                          priority="high",
                          note=f"{user} resubbed ({months} months)")
        logger.info(f"Resub announced: {user} ({months} months)")

    def note_gift_recipient(self, event: dict) -> None:
        """A channel.subscribe carrying is_gift: one recipient of a gift bomb.

        Deliberately silent. Twitch sends one of these per recipient, so
        announcing them meant N messages for a single gift -- each crediting
        the recipient as the gifter and claiming one sub. The gift event
        (handle_gift_sub) is the one that names the gifter and the count.
        The recipient is still remembered so the co-host can call back to it.
        """
        recipient = event.get('user_name', 'someone')
        self.gift_recipients.append(recipient)
        logger.debug(f"Gift recipient noted (not announced): {recipient}")

    async def handle_gift_sub(self, event: dict):
        """Handle a gift-sub bomb: one event per gift, whatever the count."""
        if not self.enabled:
            return

        # channel.subscription.gift: user_* is the GIFTER (null when
        # anonymous), total is this gift's count, cumulative_total is their
        # lifetime count on the channel (null when anonymous).
        anonymous = bool(event.get('is_anonymous'))
        user = 'Anonymous' if anonymous else (event.get('user_name') or 'Anonymous')
        try:
            count = max(1, int(event.get('total') or 1))
        except (TypeError, ValueError):
            count = 1
        tier_names = {'1000': 'Tier 1', '2000': 'Tier 2', '3000': 'Tier 3'}
        tier_name = tier_names.get(str(event.get('tier', '1000')), 'Tier 1')

        recipients = self.gift_recipients[-count:]
        self.gift_recipients = []

        plural = "subscription" if count == 1 else "subscriptions"
        scenario = (f"{user} just gifted {count} {tier_name} {plural} to the community. "
                    f"React in character in one short line -- real money, make it land.")
        if anonymous:
            scenario += " The gifter chose to stay anonymous."
        if count >= 5:
            scenario += f" {count} at once is a big drop, treat it that way."
        if recipients and count <= 3:
            scenario += f" It went to: {', '.join(recipients)}."
        cumulative = event.get('cumulative_total')
        if not anonymous and cumulative and int(cumulative) > count:
            scenario += f" They have gifted {cumulative} on this channel in total."

        await self._react(
            scenario=scenario,
            actor=user,
            fallback=random.choice(self.gift_sub_messages).format(user=user, count=count),
            priority="high",
            note=f"{user} gifted {count} sub(s)",
        )
        logger.info(f"Gift sub announced: {user} ({count} gifts, {tier_name})")

    async def handle_cheer(self, event: dict):
        """Handle bits/cheer event."""
        if not self.enabled:
            return

        # Anonymous cheers send user_name: null (present but null), so a
        # .get() default would leave it None and announce "None cheered".
        anonymous = bool(event.get('is_anonymous'))
        user = 'Anonymous' if anonymous else (event.get('user_name') or 'Anonymous')
        try:
            bits = max(0, int(event.get('bits') or 0))
        except (TypeError, ValueError):
            bits = 0
        cheer_message = event.get('message') or ''

        # Use big messages for large cheers
        if bits >= 1000:
            fallback = random.choice(self.big_cheer_messages).format(user=user, bits=bits)
            size = "a massive cheer of"
        else:
            fallback = random.choice(self.cheer_messages).format(user=user, bits=bits)
            size = "a cheer of"

        scenario = (f"{user} just dropped {size} {bits} bits. React in character "
                    f"in one short line -- real money, make it land.")
        if anonymous:
            scenario += " They cheered anonymously, so do not guess who it was."

        # Include their message if present
        if cheer_message and len(cheer_message) < 100:
            fallback += f" \"{cheer_message}\""
            scenario += f" They attached the message: \"{cheer_message}\""

        priority = "high" if bits >= 500 else "normal"
        await self._react(scenario=scenario, actor=user, fallback=fallback,
                          priority=priority, note=f"{user} cheered {bits} bits")
        logger.info(f"Cheer announced: {user} ({bits} bits)")

    async def handle_redemption(self, event: dict):
        """Handle a channel point redemption.

        Points are the one currency a viewer earns by simply being present,
        so a redemption is a deliberate ask and deserves a reaction. The
        reward TITLE is what matters -- "Hydrate!" and "Say something nice
        about my cat" want very different lines -- and the user's typed input
        is included when the reward takes one.
        """
        if not self.enabled:
            return

        user = event.get('user_name') or event.get('user_login') or 'Someone'
        reward = (event.get('reward') or {})

        now = datetime.now()
        if self.last_redemption_time:
            elapsed = (now - self.last_redemption_time).total_seconds()
            if elapsed < self.redemption_cooldown:
                self.redemptions_suppressed += 1
                logger.info(
                    f"Redemption not announced (cooldown, {elapsed:.0f}s of "
                    f"{self.redemption_cooldown}s): {user}")
                return
        self.last_redemption_time = now
        title = (reward.get('title') or '').strip() or 'a reward'
        try:
            cost = max(0, int(reward.get('cost') or 0))
        except (TypeError, ValueError):
            cost = 0
        user_input = (event.get('user_input') or '').strip()

        fallback = f"{user} redeemed {title}!"
        scenario = (f"{user} spent {cost} channel points to redeem "
                    f"\"{title}\". React in character in one short line. "
                    f"React to what the reward actually asks for, not to the "
                    f"points.")
        if user_input:
            clipped = user_input[:160]
            fallback += f" \"{clipped}\""
            scenario += f" They wrote: \"{clipped}\""

        await self._react(scenario=scenario, actor=user, fallback=fallback,
                          priority="normal",
                          note=f"{user} redeemed {title} ({cost} points)")
        logger.info(f"Redemption announced: {user} -> {title} ({cost} points)")

    async def _react(self, scenario: str, actor: str, fallback: str,
                     priority: str = "normal", note: Optional[str] = None) -> None:
        """React in character to a channel event, then announce it.

        `scenario` is what happened, in plain words -- it becomes the turn the
        model responds to. `fallback` is the template line used when the LLM
        path is disabled, unavailable, slow or empty, so an event always gets
        announced. `note` (defaults to the scenario) is what the session
        summary and recap remember, so later banter can call back to it.
        """
        message = None
        if self.llm_reactions:
            engine = getattr(self.bot, 'personality_engine', None)
            if engine is not None:
                try:
                    response = await asyncio.wait_for(
                        engine.generate_response(
                            message=scenario,
                            context=self._reaction_context(),
                            user=actor,
                            is_mention=True,   # events are never optional
                        ),
                        timeout=self.reaction_timeout,
                    )
                    if response and (response.get('text') or '').strip():
                        message = response['text'].strip()
                        self.reactions_generated += 1
                except asyncio.TimeoutError:
                    logger.warning(f"Event reaction timed out after "
                                   f"{self.reaction_timeout:.0f}s; using template")
                except Exception as e:  # noqa: BLE001 - never lose the event
                    logger.warning(f"Event reaction failed ({e}); using template")

        if message is None:
            message = fallback
            self.reactions_fell_back += 1

        await self._announce(message, priority=priority)
        self._remember(note or scenario)

    def _reaction_context(self) -> dict:
        """Same situational awareness the chat path gets: what is being
        played, what has happened this stream, what chat just said."""
        context = {}
        channel = ''
        try:
            channel = self.bot.config.get('TWITCH_CHANNEL', '')
        except Exception:  # noqa: BLE001
            pass
        buffer = getattr(self.bot, 'chat_buffer', None)
        if buffer is not None:
            try:
                context['recent_messages'] = buffer.get_recent(channel, limit=10)
            except Exception:  # noqa: BLE001
                pass
        info = getattr(self.bot, 'stream_info', None)
        if info is not None:
            try:
                context['stream_now'] = info.describe()
            except Exception:  # noqa: BLE001
                pass
        summarizer = getattr(self.bot, 'session_summarizer', None)
        if summarizer is not None:
            try:
                context['session_summary'] = summarizer.get_summary(channel)
            except Exception:  # noqa: BLE001
                pass
        return context

    def _remember(self, note: str) -> None:
        """Record the event where the co-host's memory can reach it."""
        summarizer = getattr(self.bot, 'session_summarizer', None)
        if summarizer is not None:
            try:
                summarizer.note_event(self.bot.config.get('TWITCH_CHANNEL', ''), note)
            except Exception as e:  # noqa: BLE001
                logger.debug(f"Could not note event in summary: {e}")
        recap = getattr(self.bot, 'stream_recap', None)
        if recap is not None:
            try:
                recap.record_event(note)
            except Exception as e:  # noqa: BLE001
                logger.debug(f"Could not record event in recap: {e}")

    def stats(self) -> dict:
        return {
            'enabled': self.enabled,
            'llm_reactions': self.llm_reactions,
            'reactions_generated': self.reactions_generated,
            'reactions_fell_back': self.reactions_fell_back,
            'redemptions_suppressed': self.redemptions_suppressed,
        }

    async def _announce(self, message: str, priority: str = "normal"):
        """Send announcement to chat and TTS."""
        try:
            # Send to chat
            if hasattr(self.bot, 'twitch_client') and self.bot.twitch_client:
                await self.bot.twitch_client.send_message(message)

            # Queue TTS. Route through queue_audio with the event's priority
            # (the old speak() fallback dropped priority and doesn't exist on
            # OptimizedAudioQueue -- it AttributeError'd if ever reached).
            if hasattr(self.bot, 'audio_queue') and self.bot.audio_queue:
                await self.bot.audio_queue.queue_audio(message, priority=priority)

        except Exception as e:
            logger.error(f"Failed to announce: {e}")

    def toggle(self) -> bool:
        """Toggle announcer on/off."""
        self.enabled = not self.enabled
        return self.enabled
